language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run coverage
env:
  global:
    # FIREBASE_TOKEN
    - secure: I4XCIiuB1XkHIRsjw4A7ZEPe6eg3hmCEQU62jp6bkjy2dgnf8H3ZK1eNMckBVfC7aovreUBhzx/9U769wQR1fx+YDlnALGerfSZwXDs/GRv8tawN0yV4/50z8orDykN/ZgR+PZzMZn5H7Ht+tqGYHw0MmOhny8PmXzZB2zNTecvqXUn59s2nqzSahDe9p3vPv2a0x+pnwxohs7+DYR18usGh8kDhx0gYsBBvN4oZX+oVaVlmUqnmWf4P9ddEOGWc2kWKEV/HwNqFkunRX8UyUUrVjdoX4K4Zd3NabWObuUEZmNaqaPcPBCNhOmUPYM0oiPFHRkA8c7tRrjUI8tZ+TAH0E878eqt4PfH94sA+DnDSxjHeDSou7gSKvUURwH5adjvf4NvcqNkdtpAzlLqtEPiRoE/sTxKDuwe5dHkBnlO2hO5XGhF7QYizFc+IgGHtS+WT0FIkJQH0QR4I/wfraX1oD/wZ0qMaqx1hHG6ipPjnHo8VJgN3JqpoYTWhetQsk0AFr+luZmyZ1Yiskw4wi3ra2j1bNaiwDRP0XbP7C3Ns2uW7OBs3lPPVOdgqfwDpliTakTRo4rWhIGO6OmyGOYKh4crFzbNxV0lRTbfXaRMcTXR/DlIo5Bbnaf3oC4tgM26hFAP41/4MqfqSsVtzjpUSc8yFTf/3UB0MdLihWIE=
    # FIREBASE_SECRET
    - secure: yuB+j6t9IByHBslf5WFIQinVtqlQa3CwZY4YYqdXffsFpgNGlDrG/q8wxxIfl2M0t96eQSHN7Lc7vLjg/iYxkrdGL6AnDSd6Ar9+Ys7pDZe6lC2GP5d4VnTOkFmfrqxUhCoGQZTxUDHO1lFAB+ObmS8k9YWflzoZ6l7pa5c34IS1Uf34ZaBKsXljSkj4c2YElEd8N01NQQTTGuyzt4twYXCVvEI3Kx5CZXFxYip1uODZH0sbM4uUnvDM5f5FpwD4oc7NoXuFGWzo3JAAnkBTZhmlDMmqUBQP+dMNY5hRO7quqlbvR5J49Uh9vr6i9hu4Sy1aWJDR3f2p6L4wE2yE/4Ak1RmmfAoO4nHnc5BILYBFCaL/HVA+Lq9S2/1cJYzi5wh66eFVTvVzGu3R0KRxZb1VjWIB72RZ7vWwv7hOywg5Ssjy5h/tjKkTyaRbExdwuJRJdMPJlZ9mcXpfQakHCvnnVvDkY/zZ1kZ2jScWlbeXnlPrj9c58rB2PaIIvW8FvG0U1+AHbZKvNIlvcdIYNqKGwdsdctNFAHemF9JP/u38IJQ/0VbZsDY3YaXzaH/fF9gbeciaDBpRQRiJhu8mRrJ2lNSwotWPCA5Mkfmr5F6O8weYNUjr58ol7rBobUyIzW7BW85pkJpLAFPz6DZZLwHZ1/a34xLyil4HqWN+lwo=
